# Dockerfile for React client only

FROM node:14.20.0-alpine3.16 as build-step

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# add app
COPY ./src ./src
COPY ./public ./public

# install app dependencies
COPY package.json yarn.lock ./
RUN yarn install
RUN yarn build

FROM nginx:stable-alpine
COPY --from=build-step /app/build /usr/share/nginx/html
COPY deployment/nginx.default.conf /etc/nginx/conf.d/default.conf