# Dockerfile for Flask app only

FROM python:3.7-alpine3.16

WORKDIR /app

COPY server/requirements.txt server/app.py server/.env ./
RUN pip install --no-cache-dir -r requirements.txt
ENV FLASK_ENV production

EXPOSE 3000
CMD ["gunicorn", "app:app"]