FROM node:14.20.0-alpine3.16 as build-step
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./src ./src
COPY ./public ./public
COPY package.json yarn.lock ./
RUN yarn install
CMD ["yarn", "dev"]